### ISSUE TITLE
Minor road suggestions connect to motorway

### ISSUE THREAD

**Issue by fqdb** [facebookincubator/RapiD#102]
I found at least in a few cases, a road was suggested to connect directly to a motorway. This would be extremely uncommon in reality and better to be avoided to prevent errors. I would suggest that an exception is made for ways of type motorway, and never connect roads to those.

[Desktop 2020.01.16 - 15.31.36.04.mp4.zip](https://github.com/facebookincubator/RapiD/files/4071780/Desktop.2020.01.16.-.15.31.36.04.mp4.zip)

**Comment by jeffdefacto** [comment]
This is tricky because in many developing countries, it's not uncommon for roads to directly connect to motorways.

![image](https://user-images.githubusercontent.com/17914981/72554781-3c64ce80-3850-11ea-9bb9-69defa97581f.png)

Long term, perhaps incorporating regional tagging rules into our vectorization process could help but for now it's up to the editor to make the correct decision depending on the situation.

**Comment by jjiglesiasg** [comment]
I do agree that in developing countries trunk and motorways connect directly with minor ways, including tracks. At least in Latinamerica is quite common...

**Comment by bhousel** [comment]
Closing here, as it does happen in reality sometimes.
