### ISSUE TITLE
Use best imagery

### ISSUE THREAD

**Issue by NKAmapper** [facebookincubator/RapiD#105]
RapiD is currently defaulting to Bing imagery until any other imagery has been selected. Bing has a large offset in my country, Norway, and should not be used at all. The local community gets a lot of extra work because of mappers inadvertently using Bing and other non-local imagery.

Could RapiD automatically select the imagery defined as "best" in ELI for the area being edited, as iD is doing? In the case of Norway, that would be "Norway Orthophoto".

**Comment by jeffdefacto** [comment]
Defaulting to Bing seems unintentional. It should be defaulting to the FB maxar layer.

When opening Rapid [directly in Norway](https://mapwith.ai/rapid#map=16.00/59.8917/10.7900) it is defaulting to the Norway Orthophoto, but since most people will be going to mapwith.ai/rapid and then zooming in that doesn't work. 

A potential solution for RapiD (and iD as well) would be some sort of indicator that a "default" imagery is available for an area but not currently being used. The star next to it in the background layers is probably not enough as some people rarely change imagery.

**Comment by Bonkles** [comment]
Confirmed that this is a bug that crept in during my merge with 2.17- which is when the maxar layers were removed from the imagery back-end, and I mistakenly set the same default layer as mainline iD. Fix incoming!
