### ISSUE TITLE
Are RAPID users becoming a different Breed of Mappers?

### ISSUE THREAD

**Issue by jjiglesiasg** [facebookincubator/RapiD#161]
Perhaps, not the place to post this, but I start seriously thinking that the Rapid / AI asisted users are becoming a new breed of mappers, more focused on map (roads/rivers) completeness than other more "decorative" features" of the Map.

Just a 2 cents thinking...

**Comment by gaoxm** [comment]
With the help of street view imagery and aerial imagery, it is actually possible to have AI assistance for mapping "decorative" features, e.g. surface of roads or whether they have streetlights along the side. Though I'd rather call them "rich metadata of features", or "more detailed map features" 😄 . We do think along this direction and hopefully can have better support for this in the future.

@jjiglesiasg I'll close this since it's not a feature request or bug report. Thanks for the discussion and feel free to share your ideas and suggestions in our [mapwithai_feedback slack channel](https://osmus.slack.com/archives/CK3BZ8FC0) :).
