### ISSUE TITLE
Unexpected behavior: AI-detected feature outside the assigned task

### ISSUE THREAD

**Issue by govvin** [facebookincubator/RapiD#21]
Sometimes, some AI-detected features appear outside a [task area](https://tasks-assisted.hotosm.org/project/9?task=183), like this one:

![image](https://user-images.githubusercontent.com/5821688/63205324-5e0d2e80-c0d5-11e9-91f1-d3b4a68dfbc8.png)

The instructions tocontributors is to avoid working outside the task they selected. 

In this instance, the AI-detected feature is actually outside of any defined task for the project, although there are many others nearby:
![image](https://user-images.githubusercontent.com/5821688/63205343-aa586e80-c0d5-11e9-80c3-9d5a28884aaf.png)

**Comment by gaoxm** [comment]
Thanks for reporting this @govvin ! We do have issues with cropping roads by random polygon shapes. We will investigate this and let you know if a fix is expected soon. Could you please share the RapiD link for your task? That will help us debug; thanks!

**Comment by govvin** [comment]
It was in this [task](https://tasks-assisted.hotosm.org/project/9?task=183).

**Comment by gaoxm** [comment]
Sorry about the late follow up @govvin!

I looked into the issue and believe that the road appears outside of the polygon is because it's still within the overall bounding box for the multipolygon of the task. Right now we use the overall bounding box for cropping roads because supporting arbitrary multipolygon shape is more computationally intensive and may incur longer latency from our backend service. So we choose to trade off road cropping accuracy for better performance of the tool. I think this is fine overall since mappers always have the option of not adding the road outside of the task boundaries. But we will add a clarification about this in our FAQ page.

**Comment by gaoxm** [comment]
Added a FAQ about this in https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki/FAQ.

Closing the issue for now since we don't plan to support arbitrary task shapes in the short term. Thanks again to @govvin for reporting! We can re-open it the future when we are ready to add the support.
