### ISSUE TITLE
Create like a "To-be-Continued" Node Tag

### ISSUE THREAD

**Issue by jjiglesiasg** [facebookincubator/RapiD#222]
Like ID have the "NoExit" node Tag, RAPID should have like a "To-be-Continued" node Tag, so pleople could mark up to the portion of the Road validated from AI, and them left to a future edition the continuation of such way, by the same mapper or another.

**Comment by bhousel** [comment]
[`noexit=yes`](https://wiki.openstreetmap.org/wiki/Key:noexit) is an accepted tag in OSM with extensive usage, so that's why iD (and RapiD) is able to offer a preset for it.  I don't think there is a similarly accepted tag for the idea of "to be continued", so we wouldn't be able to invent a tag for this (if I am wrong, let me know!)

But!  I think most mappers are already using [OSM Notes](https://wiki.openstreetmap.org/wiki/Notes) for this idea.  Notes are used for cases like this where you want to leave a sticky note for yourself or a future mapper.

RapiD **does** include support for OSM Notes - you just need to enable it from the "Map Data" pane.  From there you can inspect the notes left on the map by anyone, close them, or add new ones. 

Let me know if this feature gives you what you need!

![notes](https://user-images.githubusercontent.com/38784/119506037-8494da80-bd3b-11eb-9d56-0e765d0681af.gif)
