### ISSUE TITLE
Context menu jumps around when panning

### ISSUE THREAD

**Issue by Bonkles** [facebookincubator/RapiD#543]
Bryan discovered that the context menu bounces around a lot in weird ways when we're panning the map.

**Comment by bhousel** [comment]
example (though it's actually worse than the gif makes it look)
![bouncy menu](https://user-images.githubusercontent.com/38784/183971986-69387cf9-9760-4f36-9a25-e6f60d35ee9e.gif)

This was due to a bunch of things:
- The editmenu position is anchored to a lon/lat . This means that the menu's screen position needs to be computed based on a projection like `context.projection`
- `context.projection` is only _really_ accurate when full draws happen - between draws, we introduce a transformation in the "supersurface" to avoid drawing so frequently.
- So to fix this issue, we had to cancel out the "supersurface" transform, and recalc the editmenu position whenever the map moves (which is more frequent than whenever the pixi draws).
