### ISSUE TITLE
Can't Create Area With Tools

### ISSUE THREAD

**Issue by flow-enol** [facebookincubator/RapiD#553]
### Description

Areas don't generate when using the "Line" or "Area" tool:

(1) When using the "Area" tool:

> - No graphics are generated at all. When clicking on the map to start the edit, the starting node doesn't appear, and clicking again to place the next node just ends the edit with nothing produced. After the edit is 'done', the "Save" button highlights as if a feature was created.

(2) When using the "Line" tool:

> - The last segment of a polygon does not generate.
_Ex_: Only 3 sides of a square generate after double-clicking on the start node to complete the shape.

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Opera GX [LVL4 {core: 89.0.4447.98) (x86_64)}

### Steps to reproduce

(1) Select the Area tool - click on the map - click on the map at different location ~ tool stops.

(2) Select Line tool - click on the map - continue to draw a square and double-click (on start node) to complete shape ~ generates incomplete shape. 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Bing&datasets=fbRoads,msBuildings&map=21.33/34.00626/-117.92483

**Comment by Bonkles** [comment]
Since this mode isn't implemented yet I just pushed up a change to disable the mode and call out that it isn't implemented yet in the tooltip: 

<img width="410" alt="image" src="https://user-images.githubusercontent.com/1887955/185661639-7388eebf-03e4-44c6-9480-6e569cf58d49.png">

Closing since we already have bug #519 for fixing this functionality.
